version: '3'
services:

  mongodb:
    container_name: mongodb
    build: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - practica_final_bdfi_data/:/practica_final_bdfi_data
    networks:
      - practica_final_bdfi

  flask:
    container_name: flask
    build: ./flask
    ports:
      - "5000:80"
    networks:
      - practica_final_bdfi
  
  zookeeper:
    container_name: zookeeper
    build: ./zookeeper
    ports:
      - "2181:2181"
    networks:
      - practica_final_bdfi

  kafka:
    container_name: kafka
    build: ./kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - practica_final_bdfi

  spark-master:
    container_name: spark-master
    build: ./spark-master
    depends_on:
      - kafka
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./jars_dir:/opt/bitnami/spark/jars/ivy
    networks:
      - practica_final_bdfi

  spark-worker:
    container_name: spark-worker
    build: ./spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./jars_dir:/opt/bitnami/spark/jars/ivy
    networks:
      - practica_final_bdfi

networks:
  practica_final_bdfi:
    driver: bridge

volumes:
  practica_final_bdfi_data: